targets:
  $default:
    builders:
      json_serializable:
        options:
          explicit_to_json: true
      freezed:
        generate_for:
          include:
            - lib/features/*/models/*.dart
            - lib/features/*/blocs/*.dart 